#ifndef INC_CAN_PROTOCOL_H
#define INC_CAN_PROTOCOL_H

/* USER CODE BEGIN PV */


typedef enum {
	CAN_STDID_ECHO,
	CAN_STDID_ALL_PARAM,
    CAN_STDID_INFO_PARAM,

	CAN_STDID_TORQUE_ENABLE,  						
	CAN_STDID_STATE_MACHINE,			  						
	CAN_STDID_CONTROL_MODE,		

	CAN_STDID_GOAL_REVOLUTION,
	CAN_STDID_GOAL_POSITION_DEG,
	CAN_STDID_GOAL_VELOCITY_DPS,
	CAN_STDID_GOAL_TORQUE_CURRENT_MA,
	CAN_STDID_GOAL_FLUX_CURRENT_MA,

	CAN_STDID_PRESENT_REVOLUTION,
	CAN_STDID_PRESENT_POSITION_DEG,
	CAN_STDID_PRESENT_VELOCITY_DPS,
	CAN_STDID_PRESENT_TORQUE_CURRENT_MA,
	CAN_STDID_PRESENT_FLUX_CURRENT_MA,

	CAN_STDID_PRESENT_VOLTAGE,						
	CAN_STDID_PRESENT_TEMPERATURE, 				
	CAN_STDID_ZERO_DONE,			 					

    CAN_STDID_GROUP0,
    CAN_STDID_GROUP1,
    CAN_STDID_GROUP2,
    CAN_STDID_GROUP3,

} can_standard_id_t; 		//use 5 bits in 11 bits standard id length


typedef enum {
	CAN_EXTID_MODEL_NUMBER,
	CAN_EXTID_VERSION,
	CAN_EXTID_ID,             						
	CAN_EXTID_BAUD_RATE,      						
	CAN_EXTID_RECALIBRATE,

	CAN_EXTID_GEARBOX_RATIO,
	CAN_EXTID_MIN_POSITION_DEG,
	CAN_EXTID_MAX_POSITION_DEG,
	CAN_EXTID_MAX_VELOCITY_DPS,
	CAN_EXTID_MAX_ACCELERATION_DPSS,
	CAN_EXTID_MAX_CURRENT_MA,
	CAN_EXTID_RESERVED_RAM_1,						

	CAN_EXTID_TEMPERATURE_LIMIT,					
	CAN_EXTID_LOW_VOLTAGE_LIMIT,					
	CAN_EXTID_HIGH_VOLTAGE_LIMIT,					
	CAN_EXTID_MOVING_THRESHOLD_DPS,				
	CAN_EXTID_STATUS_RETURN_LVL,					
	
	CAN_EXTID_ALARM_LED,							
	CAN_EXTID_ALARM_SHUTDOWN,						
	CAN_EXTID_MOTOR_POLE_PAIRS,					
	CAN_EXTID_ELEC_SYNCHRO,
	CAN_EXTID_MOTOR_OFFSET,
	CAN_EXTID_POSITION_DEADZONE,					
	CAN_EXTID_INV_PHASE_MOTOR,
	CAN_EXTID_INV_ROTATION,

	CAN_EXTID_PID_POSITION_KP,
	CAN_EXTID_PID_POSITION_KI,
	CAN_EXTID_PID_POSITION_KD,
	CAN_EXTID_PID_VELOCITY_KP,
	CAN_EXTID_PID_VELOCITY_KI,
	CAN_EXTID_PID_VELOCITY_KD,
	CAN_EXTID_PID_VELOCITY_KFF,
	CAN_EXTID_PID_ACCELERATION_KFF,
	CAN_EXTID_PID_FLUX_CURRENT_KP,
	CAN_EXTID_PID_FLUX_CURRENT_KI,
	CAN_EXTID_PID_FLUX_CURRENT_KFF,
	CAN_EXTID_PID_TORQUE_CURRENT_KP,
	CAN_EXTID_PID_TORQUE_CURRENT_KI,
	CAN_EXTID_PID_TORQUE_CURRENT_KFF,
	CAN_EXTID_CAL_PHASE1_CURRENT_SENSE_MA,
	CAN_EXTID_CAL_PHASE1_CURRENT_SENSE_OFFSET,
	CAN_EXTID_CAL_PHASE2_CURRENT_SENSE_MA,
	CAN_EXTID_CAL_PHASE2_CURRENT_SENSE_OFFSET,
	CAN_EXTID_CAL_PHASE3_CURRENT_SENSE_MA,
	CAN_EXTID_CAL_PHASE3_CURRENT_SENSE_OFFSET,
	CAN_EXTID_CAL_VOLTAGE_SENSOR,

	CAN_EXTID_TORQUE_ENABLE,  						
	CAN_EXTID_CONTROL_MODE,		

	CAN_EXTID_GOAL_REVOLUTION,  					
	CAN_EXTID_GOAL_POSITION_DEG,
	CAN_EXTID_GOAL_VELOCITY_DPS,
	CAN_EXTID_GOAL_TORQUE_CURRENT_MA,
	CAN_EXTID_GOAL_FLUX_CURRENT_MA,
	CAN_EXTID_GOAL_RESERVED_RAM_2,					
	CAN_EXTID_GOAL_CLOSED_LOOP,

	CAN_EXTID_PRESENT_REVOLUTION,
	CAN_EXTID_PRESENT_POSITION_DEG,
	CAN_EXTID_PRESENT_VELOCITY_DPS,
	CAN_EXTID_PRESENT_TORQUE_CURRENT_MA,
	CAN_EXTID_PRESENT_FLUX_CURRENT_MA,
	CAN_EXTID_PRESENT_VOLTAGE,						
	CAN_EXTID_PRESENT_TEMPERATURE, 				
	CAN_EXTID_ZERO_DONE,
	CAN_EXTID_SAVE_CONFIG,

    CAN_EXTID_ALL_PARAM,
    CAN_EXTID_INFO_PARAM,

} can_extended_id_t; 		//use 23 bits in 29 bits extended id length



#endif
